CREATE OR REPLACE WAREHOUSE CUSTOMER_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE CUSTOMER_DB;

SHOW DATABASES;

USE DATABASE CUSTOMER_DB;

CREATE OR REPLACE SCHEMA CUSTOMER_HISTORY;

SHOW SCHEMAS;

USE WAREHOUSE CUSTOMER_WH;
USE DATABASE CUSTOMER_DB;
USE SCHEMA CUSTOMER_HISTORY;

CREATE OR REPLACE STAGE CUSTOMER_STAGE;

SHOW STAGES;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSVCUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_STAGE
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

