
--create a warehouse 
CREATE OR REPLACE WAREHOUSE CUSTOMER_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

--database creation customer_db
CREATE OR REPLACE DATABASE CUSTOMER_DB;

--schema creation customer_history
CREATE OR REPLACE SCHEMA CUSTOMER_HISTORY;

--using the newly created warehouse CUSTOMER_WH
USE WAREHOUSE CUSTOMER_WH;

--using the created database customer_db
USE DATABASE CUSTOMER_DB;

--using the created schema
USE SCHEMA CUSTOMER_HISTORY;

--stage creation
CREATE OR REPLACE STAGE CUSTOMER_STAGE;

--file format creation
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSVCUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_STAGE
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

