USE DATABASE CUSTOMER_DB;
USE SCHEMA CUSTOMER_HISTORY;
CREATE OR REPLACE TABLE RAW_DAY1(
    customer_id STRING,
    customer_name STRING,
    region STRING,
    status STRING,
    account_balance STRING,
    loaded_date STRING
);

CREATE OR REPLACE TABLE RAW_DAY2(
    customer_id STRING,
    customer_name STRING,
    region STRING,
    status STRING,
    account_balance STRING,
    loaded_date STRING
);

CREATE OR REPLACE TABLE RAW_DAY3(
    customer_id STRING,
    customer_name STRING,
    region STRING,
    status STRING,
    account_balance STRING,
    loaded_date STRING
);

CREATE OR REPLACE TABLE RAW_DAY4(
    customer_id STRING,
    customer_name STRING,
    region STRING,
    status STRING,
    account_balance STRING,
    loaded_date STRING
);


COPY INTO RAW_DAY1
FROM @CUSTOMER_STAGE/day1.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_DAY2
FROM @CUSTOMER_STAGE/day2.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_DAY3
FROM @CUSTOMER_STAGE/day3.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_DAY4
FROM @CUSTOMER_STAGE/day4.csv
FILE_FORMAT = CSV_FORMAT;

SELECT count(*) as DAY1_COUNT FROM RAW_DAY1;
SELECT count(*) as DAY2_COUNT FROM RAW_DAY2;
SELECT count(*) as DAY3_COUNT FROM RAW_DAY3;
SELECT count(*) as DAY4_COUNT FROM RAW_DAY4;

SHOW VIEWS;
SELECT * FROM TEST;

SELECT * FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_RAW;

SELECT * FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_STG;

DESCRIBE TABLE CUSTOMER_STG;

SELECT COUNT(*) FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_CURRENT;


select * from CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_CURRENT;

SELECT customer_id,
        account_balance,
        region,
        status,
        customer_state
from customer_current
where customer_id in (1003, 1005, 1006, 1007)
order by customer_id;



select * from CUSTOMER_DB.CUSTOMER_HISTORY.INT_CUSTOMER_CHANGES
order by customer_id;

SELECT * FROM CUSTOMER_DB.CUSTOMER_HISTORY.INT_CUSTOMER_CHANGES
WHERE CUSTOMER_ID = 1001;

DROP TABLE CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_HISTORY;

SELECT
    *
FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_HISTORY;

SELECT * FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_STG;

SELECT
    CUSTOMER_ID
FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_HISTORY
WHERE IS_CURRENT = TRUE;



SELECT
    *
FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_HISTORY;

SELECT * FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_HISTORY
WHERE CUSTOMER_ID = 1013;

SELECT * FROM CUSTOMER_DB.CUSTOMER_HISTORY.CUSTOMER_CURRENT;